services:
  app:
    build:
      context: ..
      dockerfile: containers/npm/Dockerfile
    stdin_open: true
    network_mode: host
    volumes:
    - ../src:/app/src
    - ../rollup.config.js:/app/rollup.config.js
    - ../package.json:/app/package.json
    - ../manifest.json:/app/manifest.json
    - ../jest.config.cjs:/app/jest.config.cjs
    - ../dist:/app/dist
    working_dir: /app
    environment:
    - TAG=${TAG:-v0.1.0}
    - REPO_NAME=${REPO_NAME:-obsidian-timestamp-utility}
    extra_hosts:
    - host.docker.internal:host-gateway
